### ISSUE TITLE
[support] Task exception was never retrieved

### ISSUE THREAD

**Issue by dmouse** [XayOn/pyrcrack#19]
I'm trying to use with the following code but I have this error

Python 3.7.9
Linux Fedora 31
Card: rtl8812au with https://github.com/aircrack-ng/rtl8812au as a driver

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<AirodumpNg.result_updater() done, defined at /.../auto/lib64/python3.7/site-packages/pyrcrack/airodump.py:82> exception=ValueError("'Station MAC, First time seen, Last time seen, Power, # packets, BSSID, Probed ESSIDs\\n' is not in list")>
Traceback (most recent call last):
  File "/.../auto/lib64/python3.7/site-packages/pyrcrack/airodump.py", line 87, in result_updater
    self.meta['result'] = self.get_results()
  File "/.../auto/lib64/python3.7/site-packages/pyrcrack/airodump.py", line 122, in get_results
    inx = lines.index('Station MAC, First time seen, Last time seen,'
ValueError: 'Station MAC, First time seen, Last time seen, Power, # packets, BSSID, Probed ESSIDs\n' is not in list
```

Code:
```
import pyrcrack
import asyncio
from contextlib import suppress

from rich.console import Console
from rich.prompt import Prompt

async def scan():
    console = Console()
    interface = "wlp0s20u3"

    async with pyrcrack.AirodumpNg() as pdump:
        await pdump.run(interface, write_interval=1)
        
        while True:
            with suppress(KeyError):
                await asyncio.sleep(2)
                ap = pdump.sorted_aps()[0]
                break

asyncio.run(scan())
```

**Comment by XayOn** [comment]
@dmouse  It would seem you're using an outdated version, could you please update it? Wich version are your using and how did you install it?

The thing is, if the results file is not written in time, it'll break with IndexError. You're only capturing "KeyError", if you did capture both KeyError and IndexError on your suppress() that'd made the trick.

But that code is *really* outdated, and current versions actually have this implemented in a completely different way.

New versions use netxml and wait for the file to be created. I also added an async iterator so the usage is far more simple, you can have a look at the current README.

**Comment by XayOn** [comment]
Wait, sorry as part of the code is using sorted_aps() I tought you were using the old code, but it's actually mixed between the previous API and the actual one.

Your code should be rewritten as:

```
import asyncio

import pyrcrack

from rich.console import Console
from rich.prompt import Prompt


async def scan_for_targets():
    """Scan for targets, return json."""
    console = Console()
    console.clear()
    console.show_cursor(False)
    airmon = pyrcrack.AirmonNg()
    #  Unless wlp0s20u3 is already on monitor mode, wich does not seem like it, you have to call airmonng to manage it.

    async with pyrcrack.AirmonNg()('wlp0s20u3') as mon:
        async with pyrcrack.AirodumpNg() as pdump:
            async for result in pdump(mon.monitor_interface):
                console.clear()
                console.print(result.table)
                await asyncio.sleep(2)


asyncio.run(scan_for_targets())
```

**Comment by XayOn** [comment]
@dmouse  David, could you try the snipped above?

**Comment by XayOn** [comment]
Closing for inactivity
