### ISSUE TITLE
README Example throws KeyError: 'monitor' in models.py

### ISSUE THREAD

**Issue by almostssh** [XayOn/pyrcrack#20]
The example from the README throws the following expections:

```
Traceback (most recent call last):
  File "pyrcrack_example/pyrcrack_tests.py", line 15, in scan_for_targets
    async for result in pdump(mon.monitor_interface):
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/airmon.py", line 47, in monitor_interface
    return iface.monitor
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/models.py", line 42, in monitor
    return self.data['monitor']['interface']
KeyError: 'monitor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyrcrack_example/pyrcrack_tests.py", line 17, in scan_for_targets
    await asyncio.sleep(2)
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/executor.py", line 179, in __aexit__
    self.proc.kill()
AttributeError: 'NoneType' object has no attribute 'kill'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyrcrack_example/pyrcrack_tests.py", line 20, in <module>
    asyncio.run(scan_for_targets())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "pyrcrack_example//pyrcrack_tests.py", line 17, in scan_for_targets
    await asyncio.sleep(2)
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/airmon.py", line 41, in __aexit__
    await self.run('stop', self.monitor_interface)
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/airmon.py", line 47, in monitor_interface
    return iface.monitor
  File "pyrcrack_example/venv/lib/python3.8/site-packages/pyrcrack/models.py", line 42, in monitor
    return self.data['monitor']['interface']
KeyError: 'monitor'

Process finished with exit code 1
```

Running python3.8 vitrual environment
Airodump-ng 1.6
Ubuntu 18.04

Editing `models.py`:
```python
    @property
    def monitor(self):
        return self.data['monitor']['interface']
```
to
```python
    @property
    def monitor(self):
        return self.data['interface']
```
prevents the error from occurring.

**Comment by XayOn** [comment]
@almostssh Could you please send the output of airmon-ng start <your_interface>?
It seems to be related to the way pyrcrack parses the monitor interface.

Your patch, however, puts the real interface in the monitor one, wich will cause problems later :-)

**Comment by CryoMyst** [comment]
Having the same issue, here is the output.
```
Found 6 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

  PID Name
  274 avahi-daemon
  282 avahi-daemon
  291 wpa_supplicant
  357 wpa_supplicant
  373 wpa_supplicant
  481 dhcpcd

PHY     Interface       Driver          Chipset

phy0    wlan0           brcmfmac        Broadcom 43430

                (mac80211 monitor mode vif enabled for [phy0]wlan0 on [phy0]wlan0mon)
                (mac80211 station mode vif disabled for [phy0]wlan0)
phy1    wlxe84e066b5386 mt7601u         Ralink Technology, Corp. MT7601U
```

**Comment by CryoMyst** [comment]
After some debugging I have made an example script as to what's happening in this instance (values copied from debugging the program).
Hope this helps.
```python
import re
MONITOR_RE = re.compile(
    r'\t\t\((\w+) (\w+) mode vif (\w+) for \[\w+\](\w+) on \[\w+\](\w+)\)')

data = [
    b'Found 6 processes that could cause trouble.',
    b"Kill them using 'airmon-ng check kill' before putting",
    b'the card in monitor mode, they will interfere by changing channels',
    b'and sometimes putting the interface back in managed mode',
    b'  PID Name',
    b'  239 avahi-daemon',
    b'  241 wpa_supplicant',
    b'  243 avahi-daemon',
    b'  356 wpa_supplicant',
    b'  381 wpa_supplicant',
    b'  481 dhcpcd',
    b'PHY\tInterface\tDriver\t\tChipset',
    b'phy0\twlan0\t\tbrcmfmac\tBroadcom 43430',
    b'\t\t(mac80211 monitor mode vif enabled for [phy0]wlan0 on [phy0]wlan0mon)',
    b'\t\t(mac80211 station mode vif disabled for [phy0]wlan0)',
    b'phy1\twlxe84e066b5386\tmt7601u\t\tRalink Technology, Corp. MT7601U'
]

pos = data.index(b'PHY	Interface	Driver		Chipset')
ifaces_data = [
    {'phy': 'phy0', 'interface': 'wlan0', 'driver': 'brcmfmac', 'chipset': 'Broadcom 43430'},
    {'phy': 'phy1', 'interface': 'wlxe84e066b5386', 'driver': 'mt7601u', 'chipset': 'Ralink Technology, Corp. MT7601U'}
]

# >>>> skips the monitor mode vif enabled line when filtering <<<<<
print(data[pos + len(ifaces_data) + 1:])

monitor_data = filter(lambda x: MONITOR_RE.match(x.decode()),
                      data[pos + len(ifaces_data) + 1:]) # Skipping
def groups(data):
    return MONITOR_RE.match(data.decode()).groups()

print(list(monitor_data))

keys = ['driver', 'mode', 'status', 'original_interface', 'interface']
monitor_data = [dict(zip(keys, groups(a))) for a in monitor_data]
print(monitor_data)```

**Comment by XayOn** [comment]
Thanks @CryoMyst, I'm adding a test to the test suite and checking it out.

**Comment by XayOn** [comment]
@CryoMyst your airmon-ng version seems to have a newline character less than mine.

Are you both running aircrack-ng 1.6? I should add to readme that it's the currently supported version (it's really only relevant if arguments change).

Anyway, skipping the +1 line in the regex should work without issues, it's just an optimization, I'm removing it and getting a new release out.

Thanks

**Comment by XayOn** [comment]
Should work on release 1.1.1 with provided data
