### ISSUE TITLE
'AirmonNg' object has no attribute 'run_args'

### ISSUE THREAD

**Issue by robbyatbln** [XayOn/pyrcrack#25]
Hi, new system but no chance, i can't  ru pyrcrack from problem to problem...can somebody helpe please?!

robby@Ubuntu1804VM:~$ python3.9 test1.py
Traceback (most recent call last):
  File "/home/robby/test1.py", line 35, in <module>
    asyncio.run(deauth())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/robby/test1.py", line 19, in deauth
    async with pyrcrack.AirmonNg() as airmon:
  File "/usr/local/lib/python3.9/dist-packages/pyrcrack/airmon.py", line 29, in __aenter__
    if not self.run_args[0][0]:
AttributeError: 'AirmonNg' object has no attribute 'run_args'

this is my test1.py -> https://raw.githubusercontent.com/XayOn/pyrcrack/develop/docs/examples/aireplay_deauth.py

**Comment by XayOn** [comment]
Hi @robbyatbln 

It was actually a bug on the example docs. It was outdated! I've updated it and added a few visual improvements to it.
