### ISSUE TITLE
ValueError: b'PHY\tInterface\tDriver\t\tChipset' is not in list Error with AirmonNg()

### ISSUE THREAD

**Issue by im-kuro** [XayOn/pyrcrack#43]
I'm making a wardriving type tool with pyrcrack and can't seem to get around this error. I've tried all kinds of different changes trying the output or if the variables where right. 

Heres the error:
```Traceback (most recent call last):
  File "/home/kali/Wardriving-CSVFiles/test.py", line 27, in <module>
    asyncio.run(scan_for_targets())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/kali/Wardriving-CSVFiles/test.py", line 17, in scan_for_targets
    choices=[a['Interface'] for a in await airmon.interfaces])
  File "/home/kali/.local/lib/python3.10/site-packages/pyrcrack/airmon.py", line 63, in interfaces
    return Interfaces(await self.readlines())
  File "/home/kali/.local/lib/python3.10/site-packages/pyrcrack/models.py", line 50, in init
    pos = data.index(b'PHY      Interface       Driver          Chipset')
ValueError: b'PHY\tInterface\tDriver\t\tChipset' is not in list```

Heres the code:

```python
import asyncio

import pyrcrack

from rich.console import Console
from rich.prompt import Prompt

airmon = pyrcrack.AirmonNg()

async def scan_for_targets():
    """Scan for targets, return json."""
    console = Console()
    airmon = pyrcrack.AirmonNg()

    InterfaceChosen = Prompt.ask(
        'Select an interface',
        choices=[a['Interface'] for a in await airmon.interfaces])

    async with airmon(InterfaceChosen) as mon:
        async with pyrcrack.AirodumpNg() as pdump:
            async for result in pdump(mon.monitor_interface):
                console.clear()
                console.print(result.table)
                await asyncio.sleep(2)


asyncio.run(scan_for_targets())
```

I'm not sure what to do as I'm running the code on kali linux for testing, though want it to run on most types of linux distros.

**Comment by rainbowflesh** [comment]
> Be sure to check the python [notebook example](https://github.com/XayOn/pyrcrack/blob/develop/docs/examples/example.ipynb).

Snap code wasn't run as expect, try this one from [example](https://github.com/XayOn/pyrcrack/blob/develop/docs/examples/init_select_recolect.py)

```python
"""Scan for targets and pretty print some data."""
import asyncio

from pyrcrack import AirmonNg, AirodumpNg, MONITOR

from rich.console import Console
from rich.prompt import Prompt

import logging

logging.basicConfig(level=logging.DEBUG)


async def scan_for_targets():
    """Scan for targets, return json."""
    console = Console()
    console.clear()
    console.show_cursor(False)
    airmon = AirmonNg()
    interfaces = await airmon.interfaces
    console.print(interfaces.table)
    interface = Prompt.ask('Select an interface',
                           choices=[str(a) for a in interfaces])
    client = None
    ap_ = None

    async with airmon(interface):
        async with AirodumpNg() as pdump:
            async for aps in pdump(MONITOR):
                console.clear()
                console.print(aps.table)
                client = Prompt.ask(
                    'Select an AP',
                    choices=['continue', *[str(a) for a in range(len(aps))]])
                if client != 'continue':
                    ap_ = aps[int(client)]
                    break

        if not ap_:
            return

        async with AirodumpNg() as pdump:
            console.print(
                ":vampire:",
                f"Selected client: [red] {ap_.bssid} [/red]")

            async for result in pdump(MONITOR, **ap_.airodump):
                console.clear()
                console.print(result.table)
                await asyncio.sleep(3)


asyncio.run(scan_for_targets())

```

**MONITOR** dependency from [feat: sparkles Improved airmon-ng interface](https://github.com/XayOn/pyrcrack/commit/10de2a00200468b1c3af66675eb7b91bdaf176e8), be sure you clone this repo's develop branch as lib to import.

**Comment by XayOn** [comment]
Notice that now Interface objects has a "interface" property, so the current recommended way would be:

```                           choices=[a.interface for a in interfaces])```

I've published a new pypi package to pypi, I'm closing this one.

Thanks!
