### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by J430N** [XayOn/pyrcrack#46]
Does anyone know how to solve this issue? I installed asyncio, pyrcrack, rich, console and prompt modules using "pip install pyrcrack" command but still got the error below when running the example code given in the [Readme.rst]. Thank you in advance.

Error:

 _make_subprocess_transport
Traceback (most recent call last):
  File "d:\Python\wifi_crack.py", line 28, in <module>
    asyncio.run(scan_for_targets())
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run    
    return loop.run_until_complete(main)
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "d:\Python\wifi_crack.py", line 18, in scan_for_targets
    choices=[a['interface'] for a in await airmon.interfaces])
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrcrack\airmon.py", line 61, in interfaces
    await self.run()
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrcrack\airmon.py", line 25, in run
    return await super().run(*args, **kwargs)
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\site-packages\pyrcrack\executor.py", line 134, in run
    self.proc = await asyncio.create_subprocess_exec(
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1670, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 394, in _make_subprocess_transport
    transp = _WindowsSubprocessTransport(self, protocol, args, shell,
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 890, in _start
    self._proc = windows_utils.Popen(
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 153, in __init__
    super().__init__(args, stdin=stdin_rfd, stdout=stdout_wfd,
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__   
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\teoja\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Code:
```python
import asyncio

import pyrcrack

from rich.console import Console
from rich.prompt import Prompt


async def scan_for_targets():
    """Scan for targets, return json."""
    console = Console()
    console.clear()
    console.show_cursor(False)
    airmon = pyrcrack.AirmonNg()

    interface = Prompt.ask(
        'Select an interface',
        choices=[a['interface'] for a in await airmon.interfaces])

    async with airmon(interface) as mon:
        async with pyrcrack.AirodumpNg() as pdump:
            async for result in pdump(mon.monitor_interface):
                console.clear()
                console.print(result.table)
                await asyncio.sleep(2)


asyncio.run(scan_for_targets()) ```

**Comment by XayOn** [comment]
Hi @J430N !

You're using pyrcrack on windows, that's a new one, we don't get many windows users around here. I'm pretty sure it SHOULD work on windows, but you need to make sure your aircrack-ng is on your PATH.

The error you're seeing there is because it's not on PATH so pyrcrack can't actually find it! :)

**Comment by J430N** [comment]
Hi, I've realized that the issue is no longer relevant and I would like to request that it be deleted.
