### ISSUE TITLE
"AssertionError" when "airmon = pyrcrack.AirmonNg()"

### ISSUE THREAD

**Issue by CommandCracker8** [XayOn/pyrcrack#47]
Hey there. When I run the example in the readme, I get the following error:
```
Traceback (most recent call last):
  File "/home/commandcracker8/Desktop/Phone-Triangulation/test.py", line 28, in <module>
    asyncio.run(scan_for_targets())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/commandcracker8/Desktop/Phone-Triangulation/test.py", line 14, in scan_for_targets
    airmon = pyrcrack.AirmonNg()
  File "/usr/local/lib/python3.10/dist-packages/pyrcrack/airmon.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyrcrack/executor.py", line 102, in __init__
    check()
  File "/usr/local/lib/python3.10/dist-packages/pyrcrack/executor.py", line 70, in check
    assert b'Aircrack-ng 1.6' in subprocess.check_output(
AssertionError
```

How do I fix this?

## Your Environment

* Python version used: 3.10.8
* Operating System: Kali GNU/Linux Rolling x86_64

**Comment by XayOn** [comment]
Which aircrack Ng version do you have? It works with 1.6 only

**Comment by CommandCracker8** [comment]
Pretty sure it's not 1.6 but I just removed the checks to make it work lmao. Quick question: how can I scan for devices like my phone? `airodump-ng` shows those but `pyrcrack` doesn't.

**Comment by XayOn** [comment]
@CommandCracker8 Yep, I'm guessing Kali does have 1.7 now, I'll be making a release shortly that only emits a warning on 1.7 (as I haven't tested it on 1.7, but should work).

How are you using it? If you're using the example, note that by default it only will show access points... and you're looking for a client :)
You can find all clients connected to an AP by using the ap object's "clients" property.

I just realized unassociated clients will probably not be accesible atm. I'm going to keep this issue open to address that limitation.

**Comment by CommandCracker8** [comment]
@XayOn Alright. Any idea when you'll be able to make unassociated clients available?

Funnily enough I was just about to ask if they can be accessed haha.

**Comment by wvthoog** [comment]
I am also interested in this
