### ISSUE TITLE
[BUG] Example fails 

### ISSUE THREAD

**Issue by xznhj8129** [XayOn/pyrcrack#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```Traceback (most recent call last):
  File "/home/anon/code/crack.py", line 28, in <module>
    asyncio.run(scan_for_targets())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/anon/code/crack.py", line 18, in scan_for_targets
    choices=[a['interface'] for a in await airmon.interfaces])
  File "/home/anon/code/crack.py", line 18, in <listcomp>
    choices=[a['interface'] for a in await airmon.interfaces])
TypeError: 'Interface' object is not subscriptable```

### Expected Behavior

_No response_

### Steps To Reproduce

run the example

### Environment

```markdown
Kernel: 5.15.0-94-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.2 Victoria
    base: Ubuntu 22.04 jammy

Python3.11 and 3.10 fail
```

**Comment by FunDan3** [comment]
It is indeed broken. the issue is in the 18'th line. What I have done there is `[str(a) for ... instead of a['interface']`.
Possibly you could do `a.interface`, idk...
